# Generated by Django 6.1.1 on 2026-09-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourstudents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
    ]
