# Generated by Django 6.1.1 on 2026-09-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourstudents', '0004_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
