# Generated by Django 6.1.1 on 2026-10-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourstudents', '0005_remove_student_enrollment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
